# Generated by Django 3.2.16 on 2022-10-29 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('tcc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcc',
            name='autor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuario.autor'),
        ),
        migrations.AddField(
            model_name='tcc',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcc.curso'),
        ),
        migrations.AddField(
            model_name='tcc',
            name='orientador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.orientador'),
        ),
    ]
