# Generated by Django 3.2.16 on 2022-11-11 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=255, verbose_name='Primeiro nome')),
                ('ultimo_nome', models.CharField(max_length=255, verbose_name='Último nome')),
                ('foto', models.ImageField(blank=True, upload_to='accounts/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('modalidade', models.IntegerField(choices=[(0, 'Bacharelado'), (1, 'Licenciatura'), (2, 'Tecnológico')])),
            ],
        ),
        migrations.CreateModel(
            name='Orientador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=255, verbose_name='Primeiro nome')),
                ('ultimo_nome', models.CharField(max_length=255, verbose_name='Último nome')),
                ('link_curriculo_lattes', models.URLField(max_length=255, verbose_name='Link do currículo lattes')),
            ],
        ),
        migrations.CreateModel(
            name='TCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('ano_de_publicacao', models.DateField(verbose_name='Ano do documento')),
                ('resumo', models.TextField(verbose_name='Resumo')),
                ('arquivo', models.FileField(upload_to='tccs', verbose_name='Arquivo')),
                ('palavras_chave', models.JSONField(default=list, verbose_name='Palavras chave')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.autor', verbose_name='Autor')),
                ('orientador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.orientador')),
            ],
        ),
    ]
